/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AggregateStats = IDL.Record({
  'avgCampusInfrastructure' : IDL.Float64,
  'avgPlacementJobs' : IDL.Float64,
  'avgValueForMoney' : IDL.Float64,
  'avgHostelFood' : IDL.Float64,
  'collegeId' : IDL.Nat,
  'avgExtraCurricular' : IDL.Float64,
  'totalReviews' : IDL.Nat,
  'avgLibraryLabs' : IDL.Float64,
  'avgTeachingQuality' : IDL.Float64,
});
export const College = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'collegeType' : IDL.Text,
  'affiliation' : IDL.Text,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'reportCount' : IDL.Nat,
  'teachingQuality' : IDL.Nat,
  'feedbackText' : IDL.Text,
  'placementJobs' : IDL.Nat,
  'reviewerName' : IDL.Text,
  'valueForMoney' : IDL.Nat,
  'collegeId' : IDL.Nat,
  'isHidden' : IDL.Bool,
  'timestamp' : Time,
  'ipHash' : IDL.Text,
  'libraryLabs' : IDL.Nat,
  'extraCurricular' : IDL.Nat,
  'campusInfrastructure' : IDL.Nat,
  'hostelFood' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'getAggregateStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AggregateStats)],
      ['query'],
    ),
  'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlaggedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsByCollege' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hideReview' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportReview' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCollegesByName' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'submitReview' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'unhideReview' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AggregateStats = IDL.Record({
    'avgCampusInfrastructure' : IDL.Float64,
    'avgPlacementJobs' : IDL.Float64,
    'avgValueForMoney' : IDL.Float64,
    'avgHostelFood' : IDL.Float64,
    'collegeId' : IDL.Nat,
    'avgExtraCurricular' : IDL.Float64,
    'totalReviews' : IDL.Nat,
    'avgLibraryLabs' : IDL.Float64,
    'avgTeachingQuality' : IDL.Float64,
  });
  const College = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'collegeType' : IDL.Text,
    'affiliation' : IDL.Text,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'reportCount' : IDL.Nat,
    'teachingQuality' : IDL.Nat,
    'feedbackText' : IDL.Text,
    'placementJobs' : IDL.Nat,
    'reviewerName' : IDL.Text,
    'valueForMoney' : IDL.Nat,
    'collegeId' : IDL.Nat,
    'isHidden' : IDL.Bool,
    'timestamp' : Time,
    'ipHash' : IDL.Text,
    'libraryLabs' : IDL.Nat,
    'extraCurricular' : IDL.Nat,
    'campusInfrastructure' : IDL.Nat,
    'hostelFood' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'getAggregateStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AggregateStats)],
        ['query'],
      ),
    'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlaggedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsByCollege' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hideReview' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportReview' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCollegesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(College)],
        ['query'],
      ),
    'submitReview' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'unhideReview' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };