/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregateStats {
  'avgCampusInfrastructure' : number,
  'avgPlacementJobs' : number,
  'avgValueForMoney' : number,
  'avgHostelFood' : number,
  'collegeId' : bigint,
  'avgExtraCurricular' : number,
  'totalReviews' : bigint,
  'avgLibraryLabs' : number,
  'avgTeachingQuality' : number,
}
export interface College {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'collegeType' : string,
  'affiliation' : string,
}
export interface Review {
  'reportCount' : bigint,
  'teachingQuality' : bigint,
  'feedbackText' : string,
  'placementJobs' : bigint,
  'reviewerName' : string,
  'valueForMoney' : bigint,
  'collegeId' : bigint,
  'isHidden' : boolean,
  'timestamp' : Time,
  'ipHash' : string,
  'libraryLabs' : bigint,
  'extraCurricular' : bigint,
  'campusInfrastructure' : bigint,
  'hostelFood' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollege' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'getAggregateStats' : ActorMethod<[bigint], [] | [AggregateStats]>,
  'getAllColleges' : ActorMethod<[], Array<College>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFlaggedReviews' : ActorMethod<[], Array<Review>>,
  'getReviewsByCollege' : ActorMethod<[bigint], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hideReview' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportReview' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCollegesByName' : ActorMethod<[string], Array<College>>,
  'submitReview' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
    ],
    undefined
  >,
  'unhideReview' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];